[package]
name = "teamhydrogen/hydrogen"
version = "0.4.2"
description = "Game framework for Roblox with all the essentials needed!"
authors = ["iSophes"]
repository = "https://github.com/teamhydrogen/hydrogen"
license = "MIT"

[target]
environment = "shared"
main = "src/init.luau"
includes = ["LICENSE", "src/**/*.luau", "README.md"]
