[package]
name = "teamhydrogen/hydrogen"
version = "0.3.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Sophie B"]
include = ["default.project.json", "LICENSE", "src"]
exclude = [
    ".github",
    ".lune",
    ".pesde",
    "docs",
    "luau_packages",
    "lune_packages",
    "Test",
    ".gitignore",
    ".luaurc",
    ".styluaignore",
    "network.zap",
    "package.json",
    "package-lock.json",
    "pesde.lock",
    "pesde.toml",
    "README.md",
    "rokit.toml",
    "selene.toml",
    "sourcemap.json",
    "test.project.json",
    "CREDITS.md",
    "Desktop.ini"

]
